### ISSUE TITLE
Remove aws-sdk dependency to reduce package size

### ISSUE THREAD

**Issue by billynorris** [getndazn/dazn-lambda-powertools#68]
# This is a Feature Proposal

## Description
This will help reduce the size of the packages uploaded to lambda, making them viewable in the AWS console.

This impacts the following middlewares;
lambda-powertools-kinesis-client
lambda-powertools-lambda-client
lambda-powertools-sns-client
lambda-powertools-sqs-client
lambda-powertools-step-functions-client

**Comment by theburningmonk** [comment]
@billynorris I don't think that's possible given our approach. What's your use case? Is the package size actually a problem? If the problem is the space, then we can also distribute all the powertools as a Lambda layer.

P.s. those are not middlewares and are clients libraries that you only need to bring in if you need them (in place of the regular AWS SDK clients)

**Comment by billynorris** [comment]
My use case was to use the lambda-powertools-lambda-client to invoke lambda from a lambda.

For tracing purposes, it's easier if the code is viewable within the AWS console. The aws-sdk dependency being ~5.8MB by itself takes it over the 3MB limit.

As a workaround I added the "__context__" object to the lambda payload so I could still use the correlation id functionality of the powertools.

**Comment by theburningmonk** [comment]
If that's the case, then we can package up all the powertools and make them available as a single Lambda layer.

**Comment by theburningmonk** [comment]
The layer was deployed as part of #94 see the README for how to install via layer
