### ISSUE TITLE
NPM @perform packages removed

### ISSUE THREAD

**Issue by stavros-zavrakas** [getndazn/dazn-lambda-powertools#85]
We are using the packages that you've published under the @perform namespace and I just found out that those modules are not published anymore and they are published under @dazn namespace. Is it possible to bring them back and mark them as deprecated?

**Comment by theburningmonk** [comment]
@simontabor @gsingh1 can you guys help here?

**Comment by theburningmonk** [comment]
@stavros-zavrakas are you able to move to the new @dazn namespace instead?

**Comment by gsingh1** [comment]
@stavros-zavrakas Those packages were marked as deprecated for 1 month period and have now been unpublished. Unfortunately, we are unable to bring them back and you will have to migrate over to @dazn org namespace from now.

**Comment by stavros-zavrakas** [comment]
@theburningmonk this is what I end up doing but I some of the published versions seems that are not consistent. I was using all the 1.5.0 @perform versions for lambda-powertools-middleware-correlation-ids there is no 1.5.0 in the @dazn namespace. Are there any breaking changes if I start using the 1.8.0?

**Comment by gsingh1** [comment]
@stavros-zavrakas  There should be no breaking changes. We follow conventional commits and semantic release versioning so you can expect breaking changes in a major version bump. You should be able to update to 1.8.0 with no issues, Apologies for this change, it was due to a few legality issues which is why we had to migrate to a new namespace.
