### ISSUE TITLE
SQS : http now unsupported is a breaking change

### ISSUE THREAD

**Issue by ilan-deepreach** [getndazn/dazn-lambda-powertools#89]
# This is a Bug Report

## Description

* What went wrong?
Breaking change in minor version update
In 1.8.0 of sqs package you're using a https agent. We were using 1.5 with former name now under the new name you didn't publish 1.5.0 of some package which forced upgrade to 1.8.0 which break our http request (localstack). We're transitioning away from http when using localstack but as default SSL localstack are obviously self certified it's a bit of a struggle as we now have to rewrite you're ssl agent so it doesn't check certificate.
We end up updating AWS to have a simple HTTP (non S) agent.
* What did you expect should have happened?
Minor version bump should not break the existing usage of a package (if you care about semver)
* What was the config (if any) you used?
* What stacktrace or error message did you see?
http request are rejected expecting https

Similar or dependent issues:
* #12345

## Additional Data

* ***Which powertool package are you using?***:
sqs
* ***Which version are you using?***:
1.8.0 1.5.0 was working
* ***Middy engine version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by theburningmonk** [comment]
@ilan-deepreach first of all, apologies as we didn't consider this use case at all, which is why we didn't consider it a breaking change - it had no breaking change to the existing contract. Due to a legal issue, we had to move the packages to the new name. Unfortunately, the two things together have made your life difficult.

@simontabor @gsingh1 what if we only set the SSL agent when we are running inside AWS? e.g. we can check against the [reserved env vars](https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html) like `AWS_LAMBDA_RUNTIME_API` or `LAMBDA_RUNTIME_DIR`, and only set the SSL agent if those env vars are present.

@ilan-deepreach what are you using to run the code locally? severless-offline? SAM? Can you check if those env vars are set even when you're running locally?

**Comment by theburningmonk** [comment]
Since AWS SDK v2.263.0 has built-in support for enabling HTTP keepalive, so we can actually just get rid of the code we have for doing that ourselves.

@simontabor @gsingh1

**Comment by gsingh1** [comment]
agreed, we can just get rid of the whole thing now 👍

**Comment by ilan-deepreach** [comment]
@theburningmonk no problem.
We use localstack with sam local
Glad the problem is going to be solved with new SDK.
Anyway we just end up updating the AWS config to use an http agent on localDev so it's okay on our side.
Thanks for your work, we very much appreciate your work in my company :+1:
